version: '3'
services:
  redis:
    restart: always
    image: redis:latest
    container_name: cache
    expose:
      - 6379

  mongo:
    restart: always
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=worker
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=superpassword
    volumes:
      - ${MONGO_CONFIG}/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ${MONGO_DATA}:/data/db
    ports:
      - '27017-27019:27017-27019'

networks:
  default:
    external:
      name: worker
